name: CI/CD Pipeline

on:
  pull_request:
    branches: [ deployment ]

jobs:
  build:
    runs-on: self-hosted
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build Docker image
        run: |
          COMMIT_HASH=$(git rev-parse --short HEAD)
          docker build -t user-service-image:$COMMIT_HASH .
          docker tag user-service-image:$COMMIT_HASH user-service-image:latest
    

      - name: Install kubectl
        run: |
          curl -LO "https://dl.k8s.io/release/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl"
          chmod +x kubectl
          sudo mv kubectl /usr/local/bin/

      - name: Deploy to Minikube
        run: |
          COMMIT_HASH=$(git rev-parse --short HEAD)
          kubectl set image deployment/user-service-deployment \
            user-service=user-service-image:$COMMIT_HASH
