name: CI/CD Pipeline

on:
  push:
    branches: [ exercise3-UserService ]

jobs:
  build:
    runs-on: self-hosted
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build Docker image
        run: docker build -t user-service-image:latest .

      - name: Deploy to Minikube
        run: kubectl apply -f k8s/